apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: webapp:beta
          name: webapp
          ports:
            - containerPort: 5000
---
apiVersion: v1  
kind: Service  
metadata:  
  name: webapp-service  
spec:  
  selector:  
    app: webapp
  ports:  
    - protocol: TCP  
      port: 5000
      targetPort: 5000
